### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by bokveizen** [BY571/DQN-Atari-Agents#3]
@ run_atari_dqn.py
before using variable "seed", should add
`seed = args.seed`
`run_random_policy(args.fill_buffer)` takes quite a long time, so I commented that line and now it runs well

**Comment by BY571** [comment]
hey, thank you for mentioning the bug! ill fix it! 
For the fill buffer you can just set the argument to 0. So no random samples are created and stored in the buffer before training.

If you find any other problems feel free to mention. Ill soon update the repo, make some changes in creating the evaluation data and adding IQN (+per, +noisy layer +n_step addon).
